Blogs new api
Salabim-mb/Usamodzielnieni pull request #268
Opened 2020-09-09 20:52 UTC by Miko1012

Nowe api do blogów, nowy sposób ładowania postów poprzez poszczególne tematy

2020-09-15 13:06 UTC, Miko1012 commented
wznowienie pracy

2020-09-17 14:33 UTC, Adaxelx requested changes
Brakuje obsługi filmów w treści dalej :/ większe zdjęcia w treści też się rozwalają troszkę.

Brakuje też usuwania komentarzy( tam było coś takiego że przez minutę chyba można usunąć a potem tylko moderator czy coś takiego )

2020-09-19 11:21 UTC, Adaxelx commented
I merge mastera by się przydało zrobić

2020-09-23 12:53 UTC, Adaxelx requested changes
Wszystko git tylko możesz zmergować mastera i  zmienić te alt teksty w obrazkach xd

2020-09-23 16:34 UTC, Adaxelx approved these changes

2020-09-23 16:52 UTC, merged