Zaufane telefony
Salabim-mb/Usamodzielnieni pull request #270
Opened 2020-09-18 16:21 UTC by Adaxelx

aktualnie bez testów

2020-09-19 10:56 UTC, Adaxelx commented
Testy uzupełnione

2020-09-22 12:15 UTC, Miko1012 requested changes

2020-09-22 12:15 UTC, Miko1012 commented on front-end/src/sass/pages/_contactPage.scss
> +}
jest bootstrapowy styl w-100, nie ma co mnożyć styli

2020-09-22 12:15 UTC, Miko1012 commented on front-end/src/Views/ContactPage/components/Contact/Contact.jsx
> +            </Button>
Zamiast kopiowania po naciśnięciu na numer telefonu powinno otwierać się wybieranie numeru

2020-09-22 12:15 UTC, Miko1012 commented on front-end/src/Views/ContactPage/components/Contact/Contact.jsx
> +            </Button>
https://stackoverflow.com/questions/51545064/how-to-make-phone-call-in-react-native

2020-09-22 12:15 UTC, Miko1012 commented on front-end/src/Views/ContactPage/components/Contact/Contact.jsx
> +              {contact.phone_number}
na mobile ten numer jest strasznie mały, ja bym go powiększył, wyśrodkował i usunął napis "skopiuj ten numer"

2020-09-22 12:15 UTC, Miko1012 commented on front-end/src/Views/ContactPage/components/NewContact/NewContact.jsx
> +        <Button variant="secondary" type="submit">
Przyciski przesyłania u nas w apce są fioletowe, ten jest szary

2020-09-22 16:38 UTC, Adaxelx commented on front-end/src/Views/ContactPage/components/Contact/Contact.jsx
> +            </Button>
Problem jest taki że to react-native czyli do tworzenia aplikacji na telefon, a w zwykłym reactcie ciężko mi doszukać się takiego rozwiązania ale popatrzę

2020-09-24 18:28 UTC, Miko1012 approved these changes

2020-09-24 18:36 UTC, merged